export const SET_LOADER = 'SET_LOADER', RESET_LOADER = 'RESET_LOADER', 
LOGIN = 'LOGIN', LOGOUT = 'LOGOUT', SIGNUP = 'SIGNUP';
export const GET_USER='GET_USER', GET_USERS='GET_USERS', UPDATE_USER='UPDATE_USER', CREATE_USER='CREATE_USER';
export const GET_PROJECT='GET_PROJECT', GET_PROJECTS='GET_PROJECTS', UPDATE_PROJECT='UPDATE_PROJECT', CREATE_PROJECT='CREATE_PROJECT';