export const SET_LOADER = 'SET_LOADER', RESET_LOADER = 'RESET_LOADER',
LOGIN = 'LOGIN', LOGOUT = 'LOGOUT', SIGNUP = 'SIGNUP';
export const GET_PROJECT='GET_PROJECT', GET_PROJECTS='GET_PROJECTS', UPDATE_PROJECT='UPDATE_PROJECT', CREATE_PROJECT='CREATE_PROJECT',DELETE_PROJECT='DELETE_PROJECT',REDIRECT_URI='REDIRECT_URI';
export const GET_USER='GET_USER', GET_USERS='GET_USERS', UPDATE_USER='UPDATE_USER', CREATE_USER='CREATE_USER',DELETE_USER='DELETE_USER', USER_ACTION_PERFORMED = 'USER_ACTION_PERFORMED',URER_REDIRECT_URI='URER_REDIRECT_URI';
export const GET_TASK='GET_TASK', GET_REPORT_TASK= 'GET_REPORT_TASK',GET_TASKS='GET_TASKS', UPDATE_TASK='UPDATE_TASK', CREATE_TASK='CREATE_TASK', DELETE_TASK = 'DELETE_TASK';
export const GET_ROLES='GET_ROLES';
export const GET_COMMENT='GET_COMMENT',GET_COMMENTS='GET_COMMENTS',UPDATE_COMMENT='UPDATE_COMMENT',CREATE_COMMENT='CREATE_COMMENT'
